version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/myapp

hooks:
  BeforeInstall:
    - location: scripts/clean_old_files.sh
  AfterInstall:
    - location: scripts/unzip_artifact.sh
  ApplicationStart:
    - location: scripts/start_server.sh
  ApplicationStop:
    - location: scripts/stop_server.sh
  ValidateService:
    - location: scripts/validate.sh
